version: 2

sources:
  - name: staging
    database: "{{ env_var('GCP_PROJECT') }}"
    schema: bandcamp_sales_schema

    tables:
      - name: sales_partitioned
      - name: sales_clustered
      - name: country_code_ref
